### ISSUE TITLE
Collision Handing / Update Method

### ISSUE THREAD

**Issue by lukaswelinder** [juliangruber/level-pathwise#11]
Just curious if I could get a quick answer to this one, what happens if I were to do something like `db.put([], { index: {} }, cb)` if there are already existing keys inside of the index object?

I'll be playing with it in an upcoming project, so I'll probably answer my own question shortly, but it's probably worth documenting info about how collision / updates are handled.

**Comment by juliangruber** [comment]
thanks for the issue! documented and tested in 3.0.3
